### ISSUE TITLE
Tabs GK5 - background colour

### ISSUE THREAD

**Issue by gjgorecki** [GavickPro/Tabs-GK5#28]
How I can change background colour in Tabs GK5?
I use this module under portfolio:
http://ewagrajnert-halupka.pl/
Currently I see white frame around gallery.

 Best regards
 Grzegorz

**Comment by dziudek** [comment]
Hello,

Please add in your template CSS file the following code:

``` css
.gkTabsItem {
    background: transparent!important;
}
```
